name: Deploy a InfinityFree
on:
  push:
    branches:
      - main  # Asegúrate que tu rama se llame main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Bajando el código de GitHub
        uses: actions/checkout@v3

      - name: Subiendo al servidor de InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: htdocs/
